### PR TITLE
Add live demo to README, resolves #51

### LINKED ISSUE #51: Deploy Live Demo
A live demo should be deployed and linked to the CI to always run the latest version of the code from the main branch.

### PR DESCRIPTION
**Pull request by gsanders5**
Added a live demo which is automatically updated from the main branch of the repository on git push.

### CODE REVIEW

**Comment by kai23bali** [comment]
Looks good to me

**Review by kai23bali — COMMENTED** [review]
Looks good

**Comment by gsanders5** [comment]
The issue was not merged and was closed as rejected. Please re-review

**Review by kai23bali — APPROVED** [review]

**Review by cjclmemphis — APPROVED** [review]
All good

**Pull request merged**
